FROM tomcat:latest
# Take the war and copy to webapps of tomcat
COPY target/hello-world-war-1.0.0.war /usr/local/tomcat/webapps/ROOT.war
copy target/hello-world-war-1.0.0/ /usr/local/tomcat/webapps/ROOT


EXPOSE 8080